### PR TITLE
input_path, output_path, and replace arguments added

### PR DESCRIPTION
**Pull request by jsaporta**

### CODE REVIEW

**Comment by jsaporta** [comment]
I've tried out the replace argument a bit, and I think it's working as intended, but I don't want to really put it in until it's been tried a bit more. Maybe we can test it somehow?

**Comment by gbasulto** [comment]
I tried to use it with and without specifying the file extension. In both cases I get the error after typing the new name:
"TypeError: Object does not appear to be a 8-bit string path or a Python file-like object"

I'll try to figure out tomorroe if I'm doing something wrong. The first uploaded version runs well.

**Comment by jsaporta** [comment]
I suspect that error is coming from the line `file_list = input_path.glob(f"*.{args.ext}")`. That string formatting method was only introduced in 3.6.

**Comment by gbasulto** [comment]
I've tried with 3.6.4 (after downloading Anaconda) and it's the same story. The whole output:

`
For each image, type the new name of the file. No extension necessary!

Please enter a new filename. Press [enter] to skip: img1
Traceback (most recent call last):
  File "renamer.py", line 56, in <module>
    main()
  File "renamer.py", line 50, in main
    plt.savefig(output_path / new_name, format=args.ext)
  File "/home/guillermo/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/guillermo/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/guillermo/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 185, in print_figure
    super(FigureCanvasQTAggBase, self).print_figure(*args, **kwargs)
  File "/home/guillermo/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/home/guillermo/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 526, in print_png
    self.figure.dpi, metadata=metadata)
TypeError: Object does not appear to be a 8-bit string path or a Python file-like object

`

**Pull request merged**
